Repository frc-862/thunder, pull requests merged in 2024-02, with the labels that each got.

#137 136 falconconfig restructure
  config/FalconConfig.java
  hardware/ThunderBird.java
Labels: feature

#139 Support for variable stddev on vision updates
  util/Pose4d.java
  vision/Limelight.java
Labels: vision

#142 [#141] Extends controller
  filter/XboxControllerFilter.java
Labels: feature

#144 [#143] - added motion magic tuning to FalconTuner
  tuning/FalconTuner.java
Labels: logging

#145 [#143] - fixed errors
  tuning/FalconTuner.java
Labels: bug

#147 [#146] Fixed Filters
  filter/XboxControllerFilter.java
Labels: bug

#151 [#150] Added Check for proper config
  hardware/ThunderBird.java
Labels: feature
